stoys-io/stoys-ui

src/profiler/columns.tsx
src/profiler/styles.ts

Set max for column width; add tooltip to cells

---

src/joinRates/JoinRates.tsx
src/joinRates/JoinStatistics.tsx
src/joinRates/model.ts
src/joinRates/styles.ts
src/quality/styles.ts

make join statistics smaller

---

src/graph/Graph.tsx
src/graph/constants.ts
src/graph/graph-ops.ts
src/graph/styles.ts

Highlight graph edges

---

package-lock.json
package.json
src/profiler/components/JsonDrawer.tsx
src/profiler/components/styles.ts

Big json viewer

---

src/graph/GraphComponent.tsx
src/graph/components/ConnectedDrawer.tsx
src/graph/components/Drawer.tsx
src/graph/components/DrawerTabs.tsx
src/graph/constants.ts
src/graph/graph-store.ts
src/graph/styles.ts
stories/Graph.stories.tsx

- Drawer will be opened in a graph Container, not in a window
- Drawer behavior is more independent

Attach graph drawer to its component

---

src/graph/GraphComponent.tsx
src/graph/components/Sidebar.tsx
src/graph/graph-ops.ts
src/graph/graph-store/handlers.ts
src/graph/graph-store/model.ts
src/graph/graph-store/store.ts
src/graph/model.ts
src/metrics/model.ts

- Fix metric interface 
- Improve release selection
- Fix tables and columns diffing, recalculate `diff`-ed graph

Resolve some todos

---

src/graph/components/Sidebar.tsx
src/graph/graph-color-scheme.ts
src/graph/graph-ops.ts
src/graph/graph-store/handlers.ts
src/graph/model.ts

Highlight metrics (badge)

---

src/graph/components/DagNode.tsx
src/graph/constants.ts
src/graph/graph-layout.ts
src/graph/graph-ops.ts
src/graph/graph-store/handlers.ts
src/graph/model.ts
src/graph/styles.ts

Display column types

---

src/graph/components/DagNode.tsx
src/graph/components/Sidebar.tsx
src/graph/graph-ops.ts
src/graph/graph-store/handlers.ts
src/graph/graph-store/model.ts
src/graph/graph-store/store.ts
src/graph/model.ts
src/graph/styles.ts

Metrics dropdown

---

src/graph/GraphComponent.tsx
src/graph/components/DagNode.tsx
src/graph/components/Sidebar.tsx
src/graph/graph-store/store.ts
src/graph/model.ts
src/graph/usePreventDoubleClick.ts

- Open drawer and drawer switch nodes on double click
- Column tooltips include metrics
- Add 'none' column metric

UI adjustments

---

src/graph/components/Sidebar.tsx

Dropdowns with substring search

---

src/graph/components/DagNode.tsx
src/graph/components/Sidebar.tsx
src/graph/graph-store/handlers.ts
src/graph/graph-store/model.ts
src/graph/graph-store/store.ts
src/graph/styles.ts

Add normalized count option and highlights

Display normalized count

---

src/graph/GraphComponent.tsx
src/graph/components/DagNode.tsx
src/graph/components/ScrollableSelect.tsx
src/graph/components/Sidebar.tsx
src/graph/graph-color-scheme.ts
src/graph/graph-ops.ts
src/graph/graph-store/handlers.ts
src/graph/graph-store/model.ts
src/graph/graph-store/store.ts
src/graph/styles.ts

- Highlight column metrics
- Fix for select column issue
- Display normalized count
- Prevent wheel on open dropdown

Column metric updates

---

src/graph/graph-ops.ts
src/graph/graph-store/handlers.ts
src/graph/graph-store/model.ts
src/graph/graph-store/store.ts
src/graph/graph-traversal.ts

Abstracts away column traversal. The same to be done with tables/nodes

feat(graph): update graph columns traversal

---

src/customGraph/CustomGraphComponent.tsx
src/customGraph/DagEdge.tsx
src/customGraph/DagNode.tsx
src/customGraph/GraphScreen.tsx
src/customGraph/index.ts
src/customGraph/mocks.ts
src/graph/components/Drawer.tsx
src/graph/styles.ts
stories/CustomGraph.stories.tsx

- Fix drawer resize area
- Re-enable node clicks
- Re-enable colored edges

Custom graph fixes

---

src/customGraph/CustomGraphComponent/CustomGraphComponent.tsx
src/customGraph/CustomGraphComponent/bubbleset.ts
src/customGraph/CustomGraphComponent/colors.ts
src/customGraph/GraphScreen.tsx
src/customGraph/bubblesets-js/LICENSE
src/customGraph/bubblesets-js/bubblesets.js
src/customGraph/bubblesets-js/index.ts
src/graph/model.ts
stories/mocks/graph/dag_inlined_groups.json
tsconfig.json

feat(graph): add basic bubbleset example

---

src/graph/DagNode.tsx

feat(graph): tooltip no average

---

src/graph-common/components/Sidebar.tsx
src/graph-common/model.ts
src/graph-common/ops.ts
src/graph-reactflow/DagNode.tsx
src/graph/DagNode.tsx
src/graph/TinyPmf.tsx
stories/mocks/graph/dag_inlined.json

feat(graph): tiny pmf plot

---

src/graph-common/components/DrawerTabs.tsx
src/graph-common/components/Sidebar.tsx
src/graph-common/ops.ts
src/graph-common/store/StoreProvider.tsx
src/graph-common/store/handlers.ts
src/graph-common/store/model.ts
src/graph-common/store/store.ts
src/graph-reactflow/Graph.tsx
src/graph/Graph.tsx
stories/Graph.stories.tsx

- be able to inspect the previous run graph
- remove jump to diff mode
https://user-images.githubusercontent.com/9988008/150170814-bf54b2d6-c9ae-4594-a553-0779b408a854.mov

feat(graph): be able to inspect the previous run graph

---

src/graph-common/constants.ts
src/graph-common/model.ts
src/graph/DagNode.tsx
src/graph/DiffMetric.tsx
src/graph/TableMetricIndicator.tsx

https://user-images.githubusercontent.com/9988008/150589877-27c6ab90-e1a4-4005-9a70-3ec5a6796220.mov

feat(graph): column metrics diff mode

---

src/graph/DagNode.tsx
stories/mocks/graph/20210922_120415_152372/dag_inlined.json
stories/mocks/graph/20210922_125856_444212/dag_inlined.json

feat(graph): add pmf plot diff mode

---

src/CustomGraph/CustomGraph.tsx
src/CustomGraph/ZoomUtilProvider.tsx
src/CustomGraph/constants.ts
src/CustomGraph/graph-layout.ts
src/CustomGraph/index.ts
src/CustomGraph/types.ts
src/CustomGraph/usePanZoom.ts
src/graph/Graph.tsx

https://user-images.githubusercontent.com/9988008/150787774-6ac7d65a-920c-4afc-8bc2-fdb7b192f94a.mov

feat(graph): add search jump

---

src/graph-common/components/DrawerTabs.tsx

Also change data selection logic of "diff-able" tabs

fix(graph): fix no drawer data

---

README.md
package.json

This reverts commit ba0cf8c0413866cc610e98eea9152af8a4b0aa88.

Revert "Update readme (#161)"
